## Step 1: Exogenous Shock
1. Create measure of code quality
   
    a. Measure of user-side code quality
   
    b. Measure of maintainer-side code quality
3. Analyze contributions made
4. Hypothesize how my instrument/exogenous affects either, and examine the empirical effect

## Step 2: 
How do I actually perform analysis?
1. Measure 1: Compare within repository groups
2. Measure 2: Find some other way to weight what a "download" means?

In [1]:
import os
import pandas as pd
import ast
from pandarallel import pandarallel
import glob
import json
import numpy as np
from itertools import chain

In [2]:
pandarallel.initialize(progress_bar=False)

INFO: Pandarallel will run on 8 workers.
INFO: Pandarallel will use standard multiprocessing data transfer (pipe) to transfer data between the main process and workers.

In [3]:
pd.set_option('display.max_columns', None)

In [4]:
df_repo_info = pd.DataFrame()
df_actor_info = pd.DataFrame()
df_org_info = pd.DataFrame()

In [5]:
df_pr = pd.DataFrame()
for i in range(99):
    if i < 10:
        i = f"0{i}"
    df_pr_i = pd.read_csv(f'data/github_clean/prEventCommits0000000000{i}.csv', index_col = 0)
    df_pr = pd.concat([df_pr_i[['type', 'created_at', 'repo_id', 'actor_id', 'org_id', 'pr_id',
                                'pr_number', 'pr_state', 'pr_locked', 'pr_merged_at','pr_closed_at','pr_updated_at',
                                'pr_commits', 'pr_additions','pr_deletions','pr_changed_files',
                                'pr_author_association', 'pr_assignees', 'pr_requested_reviewers', 'pr_requested_teams',
                                'pr_merged_by_login', 'pr_merged_by_id', 'pr_merged_by_type',
                                'pr_merged_by_site_admin', 'pr_label', 'commit_list',
                               ]],
                       df_pr])
    df_repo_i = df_pr_i[['repo_id', 'repo_name']].drop_duplicates()
    df_actor_i = df_pr_i[['actor_id', 'actor_login', 'repo_id', 'org_id',]].drop_duplicates()
    df_org_i = df_pr_i[['org_id', 'org_login']].drop_duplicates()

    df_repo_info = pd.concat([df_repo_info, df_repo_i]).drop_duplicates()
    df_actor_info = pd.concat([df_actor_info, df_actor_i]).drop_duplicates()
    df_org_info = pd.concat([df_org_info, df_org_i]).drop_duplicates()

In [6]:
df_pr = df_pr[~df_pr.index.isnull()]

In [7]:
%%time
files = glob.glob("data/github_clean/prReviewEvent0*")
df_pr_review_events = [pd.read_csv(f, index_col = 0) for f in files]
df_pr_review_events = pd.concat(df_pr_review_events,ignore_index=True)
df_pr_review_events = df_pr_review_events.drop_duplicates()

CPU times: user 5.57 s, sys: 1.12 s, total: 6.69 s
Wall time: 6.91 s

In [8]:
%%time
files = glob.glob("data/github_clean/prReviewCommentEvent0*")
df_pr_review_comment_events = [pd.read_csv(f, index_col = 0) for f in files]
df_pr_review_comment_events = pd.concat(df_pr_review_comment_events,ignore_index=True)
df_pr_review_comment_events = df_pr_review_comment_events.drop_duplicates()

CPU times: user 10.1 s, sys: 1.72 s, total: 11.8 s
Wall time: 12.1 s

In [9]:
review_comments_add = df_pr_review_comment_events.copy()
review_comments_add.rename({'pr_review_comment_action':'pr_review_action', 'pr_review_comment_id':'pr_review_id',
                            'pr_review_comment_body': 'pr_review_body', 'pr_review_comment_commit_id':'pr_review_commit_id',
                            'pr_review_comment_author_association':'pr_review_author_association'},
                          axis = 1, inplace = True)
review_comments_add['pr_review_state'] = 'commented'
review_comments_add.drop(['pr_review_comment_site_admin'], axis = 1, inplace = True)

In [10]:
%%time
df_pr_all_reviews = pd.concat([df_pr_review_events, review_comments_add]).drop_duplicates().reset_index(drop = True)
df_pr_all_reviews['created_at'] = pd.to_datetime(df_pr_all_reviews['created_at'])

CPU times: user 12.4 s, sys: 779 ms, total: 13.2 s
Wall time: 13.2 s

In [11]:
df_pr_all_reviews.sort_values('pr_review_body', inplace = True)
df_pr_all_reviews.drop_duplicates(subset = ['created_at', 'repo_id', 'actor_id', 'pr_review_id', 
                                            'pr_review_commit_id', 'pr_review_state'], keep = 'first', inplace = True)

In [12]:
def cleanParquetPR(file):
    try:
        df = pd.read_parquet(file,engine='fastparquet')
        return df
    except:
        print(file)
        return pd.DataFrame()

In [13]:
%%time
files = glob.glob("data/github_commits/parquet/*_pr_*")
df_parquet_pr_data = [cleanParquetPR(f) for f in files]
df_parquet_pr = pd.concat(df_parquet_pr_data,ignore_index=True)

CPU times: user 3min 21s, sys: 5min 12s, total: 8min 33s
Wall time: 10min 58s

In [14]:
%%time
df_parquet_pr.sort_values('pr_state', inplace = True)
df_parquet_pr.drop_duplicates(
    subset = ['pr_number', 'repo_id', 'repo_name', 'actor_id', 'actor_login', 'org_id', 'org_login','commit sha',
              'commit author name', 'commit author email', 'committer name', 'commmitter email', 'commit message', 'commit additions',
              'commit deletions', 'commit changes total', 'commit files changed count', 'commit time'], inplace = True)

CPU times: user 39.2 s, sys: 1min 28s, total: 2min 7s
Wall time: 2min 59s

In [15]:
df_parquet_pr['commit time'] = pd.to_datetime(df_parquet_pr['commit time'],unit='s')

In [16]:
for col in ['pr_assignees', 'pr_requested_reviewers', 'pr_requested_teams', 'pr_label', 'commit_list']:
    print(col)
    df_pr[col] = df_pr[col].apply(lambda x: [] if type(x) == float or type(x) == type(None) or \
                                  (type(x) == str and x == "'float' object has no attribute 'split'") else x)
    df_pr[col] = df_pr[col].apply(lambda x: ast.literal_eval(x) if type(x) == str else x)

pr_assignees
pr_requested_reviewers
pr_requested_teams
pr_label
commit_list

In [17]:
df_pr['pr_id'] = pd.to_numeric(df_pr['pr_id'])

In [18]:
df_pr['valid_vals'] = df_pr.count(axis = 1)
df_pr['retrieved_commits'] = df_pr['commit_list'].apply(len)

In [19]:
df_pr = df_pr.sort_values(['valid_vals', 'retrieved_commits', 'created_at'], ascending = False)

In [20]:
df_pr['actor_id_state'] = df_pr['actor_id'].astype(str)+" | " 
df_pr['actor_id_state'] = df_pr['actor_id_state'] + df_pr['pr_state'].apply(lambda x: 'NAN STATE' if type(x) != str else x) 
df_pr['actor_id_state'] = df_pr['actor_id_state'] + " | " +  df_pr['pr_author_association'].apply(lambda x: 'NAN AUTHOR ASSOCIATION' if type(x) != str else x) 


df_parquet_pr['actor_id_state'] = df_parquet_pr['actor_id'].astype(str)+" | " 
df_parquet_pr['actor_id_state'] = df_parquet_pr['actor_id_state'] + df_parquet_pr['pr_state'].apply(lambda x: 'NAN STATE' if type(x) != str else x)

In [21]:
%%time
df_pr['actor_id_list'] = df_pr['actor_id_state'].groupby(df_pr['pr_id']).transform(lambda x: [x.tolist()]*len(x))
df_pr['actor_id_list'] = df_pr['actor_id_list'].apply(np.unique)

CPU times: user 2min 27s, sys: 5min 1s, total: 7min 29s
Wall time: 10min 6s

In [22]:
df_pr_nodup = df_pr.drop_duplicates(subset = ['repo_id', 'pr_id'], keep = 'first')

In [23]:
%%time
df_parquet_pr['pr_id_temp'] = df_parquet_pr['repo_id'].astype(str)+"_"+df_parquet_pr['pr_number'].astype(str)
df_parquet_pr['actor_id_list'] = df_parquet_pr['actor_id_state'].groupby(df_parquet_pr['pr_id_temp']).transform(lambda x: [x.tolist()]*len(x))
df_parquet_pr['actor_id_list'] = df_parquet_pr['actor_id_list'].apply(np.unique)

CPU times: user 4min 5s, sys: 5min 14s, total: 9min 19s
Wall time: 12min 26s

In [24]:
df_parquet_pr_nodup = df_parquet_pr.drop_duplicates(
    subset = ['repo_id', 'pr_id_temp', 'commit time', 'commit sha'], keep = 'first')

In [25]:
df_parquet_pr_nodup['actor_id_list'] = df_parquet_pr_nodup['actor_id_list'].apply(lambda x: sorted(x))
df_pr_nodup['actor_id_list'] = df_pr_nodup['actor_id_list'].apply(lambda x: sorted(x))

/var/folders/5s/dvrxt95949x1pm_sjxm85lj00000gn/T/ipykernel_14225/2364950747.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_parquet_pr_nodup['actor_id_list'] = df_parquet_pr_nodup['actor_id_list'].apply(lambda x: sorted(x))
/var/folders/5s/dvrxt95949x1pm_sjxm85lj00000gn/T/ipykernel_14225/2364950747.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_pr_nodup['actor_id_list'] = df_pr_nodup['actor_id_list'].apply(lambda x: sorted(x))

In [28]:
df_pr_commits = pd.merge(df_pr_nodup.drop(['type', 'actor_id', 'org_id', 'pr_state', 'pr_author_association',
                                           'valid_vals','retrieved_commits'], axis =1), 
                         df_parquet_pr_nodup, 
                         on = ['repo_id', 'pr_number', ], 
                         how = 'left')

In [44]:
df_pr_commits.rename({'actor_id_state_y':'commit_actor_id_state',
                      'actor_id_state_x':'pr_actor_id_state'}, axis= 1, inplace = True)

In [51]:
df_pr_commits.rename({'actor_id_list_y':'commit_actor_id_list',
                      'actor_id_list_x':'pr_actor_id_list'}, axis= 1, inplace = True)

In [54]:
df_pr[df_pr['pr_id'] == 242615734]

,type,created_at,repo_id,actor_id,org_id,pr_id,pr_number,pr_state,pr_locked,pr_merged_at,pr_closed_at,pr_updated_at,pr_commits,pr_additions,pr_deletions,pr_changed_files,pr_author_association,pr_assignees,pr_requested_reviewers,pr_requested_teams,pr_merged_by_login,pr_merged_by_id,pr_merged_by_type,pr_merged_by_site_admin,pr_label,commit_list,valid_vals,retrieved_commits,actor_id_state,actor_id_list
61695.0,PullRequestEvent,2019-01-07 11:04:53+00:00,110677052,18406791,8576589.0,242615734,99,closed,False,2019-01-07T11:04:53Z,2019-01-07T11:04:53Z,2019-01-07T11:04:53Z,2.0,52,15,2,CONTRIBUTOR,[],[],[],PrettyWood,18406791.0,User,False,[],"[6881f10e65f17a219273b0404f990cfd7234e828, 274...",26,4,18406791 | closed | CONTRIBUTOR,"[13640018 | open | CONTRIBUTOR, 18406791 | clo..."
62087.0,PullRequestEvent,2019-01-07 10:33:18+00:00,110677052,13640018,8576589.0,242615734,99,open,False,NaN,NaN,2019-01-07T10:33:18Z,2.0,52,15,2,CONTRIBUTOR,[],[],[],NaN,NaN,NaN,NaN,[],"[6881f10e65f17a219273b0404f990cfd7234e828, 274...",20,4,13640018 | open | CONTRIBUTOR,"[13640018 | open | CONTRIBUTOR, 18406791 | clo..."

In [52]:
df_pr_commits[df_pr_commits['pr_commits'] == 2]

,created_at,repo_id,pr_id,pr_number,pr_locked,pr_merged_at,pr_closed_at,pr_updated_at,pr_commits,pr_additions,pr_deletions,pr_changed_files,pr_assignees,pr_requested_reviewers,pr_requested_teams,pr_merged_by_login,pr_merged_by_id,pr_merged_by_type,pr_merged_by_site_admin,pr_label,commit_list,pr_actor_id_state,pr_actor_id_list,repo_name,actor_id,actor_login,org_id,org_login,pr_state,commit_groups,commit sha,commit author name,commit author email,committer name,commmitter email,commit message,commit additions,commit deletions,commit changes total,commit files changed count,commit file changes,commit time,commit_actor_id_state,pr_id_temp,commit_actor_id_list
978890,2019-01-07 11:04:53+00:00,110677052,242615734,99,False,2019-01-07T11:04:53Z,2019-01-07T11:04:53Z,2019-01-07T11:04:53Z,2.0,52,15,2,[],[],[],PrettyWood,18406791.0,User,False,[],"[6881f10e65f17a219273b0404f990cfd7234e828, 274...",18406791 | closed | CONTRIBUTOR,"[13640018 | open | CONTRIBUTOR, 18406791 | clo...",ToucanToco/toucan-data-sdk,18406791.0,PrettyWood,8576589.0,ToucanToco,closed,"[e7a1a8dc52c4eadab6a427f1885fb0e7924efc7d, 688...",6881f10e65f17a219273b0404f990cfd7234e828,Luka Peschke,luka.peschke@toucantoco.com,Luka Peschke,luka.peschke@toucantoco.com,chore: Bump joblib>1\n\nSigned-off-by: Luka Pe...,187.0,184.0,371.0,2.0,"[{'file': 'poetry.lock', 'additions': 186, 'de...",2022-06-09 15:04:32,18406791 | closed,110677052_99,"[13640018 | open, 18406791 | closed]"
978891,2019-01-07 11:04:53+00:00,110677052,242615734,99,False,2019-01-07T11:04:53Z,2019-01-07T11:04:53Z,2019-01-07T11:04:53Z,2.0,52,15,2,[],[],[],PrettyWood,18406791.0,User,False,[],"[6881f10e65f17a219273b0404f990cfd7234e828, 274...",18406791 | closed | CONTRIBUTOR,"[13640018 | open | CONTRIBUTOR, 18406791 | clo...",ToucanToco/toucan-data-sdk,18406791.0,PrettyWood,8576589.0,ToucanToco,closed,"[6881f10e65f17a219273b0404f990cfd7234e828, 274...",274967127cd139ddc4b89ecb87977e2e020c0e55,Luka Peschke,luka.peschke@toucantoco.com,Luka Peschke,luka.peschke@toucantoco.com,fix(helpers): Remove @wraps in decorators\n\nS...,0.0,2.0,2.0,1.0,[{'file': 'toucan_data_sdk/utils/decorators.py...,2022-06-09 15:34:11,18406791 | closed,110677052_99,"[13640018 | open, 18406791 | closed]"
978892,2019-01-07 11:04:53+00:00,110677052,242615734,99,False,2019-01-07T11:04:53Z,2019-01-07T11:04:53Z,2019-01-07T11:04:53Z,2.0,52,15,2,[],[],[],PrettyWood,18406791.0,User,False,[],"[6881f10e65f17a219273b0404f990cfd7234e828, 274...",18406791 | closed | CONTRIBUTOR,"[13640018 | open | CONTRIBUTOR, 18406791 | clo...",ToucanToco/toucan-data-sdk,18406791.0,PrettyWood,8576589.0,ToucanToco,closed,"[274967127cd139ddc4b89ecb87977e2e020c0e55, 8a6...",8a6e37b0d13399d3991113a98f9698b19193110e,Luka Peschke,luka.peschke@toucantoco.com,Luka Peschke,luka.peschke@toucantoco.com,chore: mypy\n\nSigned-off-by: Luka Peschke <lu...,1.0,1.0,2.0,1.0,[{'file': 'toucan_data_sdk/utils/decorators.py...,2022-06-09 15:41:24,18406791 | closed,110677052_99,"[13640018 | open, 18406791 | closed]"
978893,2019-01-07 11:04:53+00:00,110677052,242615734,99,False,2019-01-07T11:04:53Z,2019-01-07T11:04:53Z,2019-01-07T11:04:53Z,2.0,52,15,2,[],[],[],PrettyWood,18406791.0,User,False,[],"[6881f10e65f17a219273b0404f990cfd7234e828, 274...",18406791 | closed | CONTRIBUTOR,"[13640018 | open | CONTRIBUTOR, 18406791 | clo...",ToucanToco/toucan-data-sdk,18406791.0,PrettyWood,8576589.0,ToucanToco,closed,"[8a6e37b0d13399d3991113a98f9698b19193110e, 58d...",58d1c065f9eb22deb45df093e1a1d7ee1cf77ae5,Luka Peschke,luka.peschke@toucantoco.com,Luka Peschke,luka.peschke@toucantoco.com,"fix: Since wraps have been removed, use f.__na...",1.0,1.0,2.0,1.0,[{'file': 'toucan_data_sdk/utils/decorators.py...,2022-06-09 15:51:18,18406791 | closed,110677052_99,"[13640018 | open, 18406791 | closed]"
1069894,2023-08-31 23:55:19+00:00,79510167,1496318901,5897,False,2023-08-31T23:55:17Z,2023-08-31T23:55:17Z,2023-08-31T23:55:18Z,2.0,5,0,2,[],[],[],matteius,479892.0,User,False,[],"[1dd7f64d0b3797115c2a489ba4cccf1d269340f7, a51...",479892 | closed | MEMBER,"[479892 | closed | MEMBER, 479892 | open | MEM...",pypa/pipenv,479892.0,matteius,647025.0,pypa,closed,"[16334c91398c5a031d5f922b7d58eff4ed7c5bd8, 1dd...",1dd7f64d0b3797115c2a489ba4cccf1d269340f7,Matt Davis,matteius@gmail.com,Matt Davis,matteius@gmail.com,Set log level in resolver to WARN when verbose...,4.0,0.0,4.0,1.0,"[{'file': 'pipenv/resolver.py', 'additions': 4...",2023-08-31 00:46:39,479892 | closed,79510167_5897,[479892 | closed]
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2408727,2018-11-19 08:32:15+00:00,25334762,231889158,209,False,NaN,NaN,2018-11-19T08:32:15Z,2.0,13,13,3,[],[],[],NaN,NaN,NaN,NaN,[],[],1103477 | open | NONE,"[1103477 | open | NONE, 824194 | closed | NONE]",pipermerriam/flex,824194.0,pipermerriam,NaN,None,closed,"[55822c2ffaa17dfa5e403d7feed898cb9bc983bb, 85e...",85e30e93ba09677515041b77cfba3c32b3b17725,Brett Randall,javabrett@gmail.com,Brett Randall,javabrett@gmail.com,setup.py: removed upper-bounds from all requir...,8.0,8.0,16.0,1.0,"[{'file': 'setup.py', 'additions': 8, 'deletio...",2018-11-19 02:44:01,824194 | closed,25334762_209,[824194 | closed]
2408728,2018-11-19 08:32:15+00:00,25334762,231889158,209,False,NaN,NaN,2018-11-19T08:32:15Z,2.0,13,13,3,[],[],[],NaN,NaN,NaN,NaN,[],[],1103477 | open | NONE,"[1103477 | open | NONE, 824194 | closed | NONE]",pipermerriam/flex,824194.0,pipermerriam,NaN,None,closed,"[85e30e93ba09677515041b77cfba3c32b3b17725, 4f6...",4f62b4fdaf36b1bbc2c24ba4856139217c936ad0,Brett Randall,javabrett@gmail.com,Brett Randall,javabrett@gmail.com,pytest: replaced deprecated pytest.mark.xfail ...,5.0,5.0,10.0,2.0,[{'file': 'tests/core/test_example_schemas.py'...,2018-11-19 04:15:16,824194 | closed,25334762_209,[824194 | closed]
2408739,2018-10-23 02:07:29+00:00,1206729,224870633,445,False,NaN,NaN,2018-10-23T02:07:29Z,2.0,26,1,2,[],[],[],NaN,NaN,NaN,NaN,[],[],150309 | open | OWNER,[150309 | open | OWNER],NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaT,NaN,NaN,NaN
2408750,2018-09-17 16:06:23+00:00,11753762,216035204,396,False,NaN,NaN,2018-09-17T16:06:22Z,2.0,16,0,2,[],[],[],NaN,NaN,NaN,NaN,[],[],11233001 | open | NONE,[11233001 | open | NONE],NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaT,NaN,NaN,NaN
2408753,2018-09-08 12:37:32+00:00,12236329,214093468,187,False,NaN,NaN,2018-09-08T12:37:32Z,2.0,15,0,1,[],[],[],NaN,NaN,NaN,NaN,[],[],7304193 | open | NONE,[7304193 | open | NONE],NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaT,NaN,NaN,NaN

In [42]:
#
# why is pr additions weird?
# aggregate commit additions
df_pr_commits[df_pr_commits['actor_id_list_y'].isnull()]['repo_id'].value_counts()

repo_id
71932349     21393
4127088      20435
136028978      547
71932349       444
4127088        400
             ...
76293715         1
6710117          1
86331895         1
25214537         1
18298291         1
Name: count, Length: 5642, dtype: int64

In [ ]:
df_pr_commits

In [ ]:
df_pr_nodup

In [ ]:
df_parquet_pr_nodup

In [ ]:
prEvent contains all the data about PRs
prEventCommit contains specificaly commit data about PRs, maps back
prReview contains data about prReviews - link to examine 1) whose reviewing, 2) whether requested teams are reviewing,
                                                         3) how many reviews
prReviewCommentEvent contains statsitics about the type of discussion that''s going on about pr reviews, look at 
1) number of comments, 2) whose commenting